Re-write brightness script on sh instead of fish

diff --git a/scripts/brightness b/scripts/brightness
--- a/scripts/brightness
+++ b/scripts/brightness
@@ -1,16 +1,53 @@
-#!/usr/bin/env fish
+#!/usr/bin/env sh
 
-argparse --ignore-unknown \
-  "u/up" "d/down" "l/level=" "s/set=" -- $argv
+SHORT_OPTS="udl:s:"
+LONG_OPTS="up,down,level:,set:"
 
-not type -q brightnessctl && exit
+OPTS=`getopt --options "${SHORT_OPTS}" \
+  --longoptions "${LONG_OPTS}" --alternative \
+  --name "adjust-brightness" -- "${@}"`
 
-set -q _flag_set && brightnessctl --quiet set "$_flag_set%" && exit
+if [[ "${?}" != 0 ]]; then
+  echo "Failed parsing options." >&2
+  exit 1
+fi
 
-if set -q _flag_level
-  if set -q _flag_up
-    brightnessctl --quiet set "+$_flag_level%"
-  else if set -q _flag_down
-    brightnessctl --quiet set "$_flag_level%-"
-  end
-end
+echo "${OPTS}"
+eval set -- "${OPTS}"
+
+UP=true
+DOWN=false
+LEVEL=5
+SET=0
+
+while true; do
+  case "${1}" in
+    '-u' | '--up' )
+      UP=true && DOWN=false; shift ;;
+    '-d' | '--down' )
+      DOWN=true && UP=false; shift ;;
+    '-l' | '--level' )
+      LEVEL="${2}"; shift 2 ;;
+    '-s' | '--set' )
+      SET="${2}"; shift 2 ;;
+    -- )
+      shift; break ;;
+    * )
+      break ;;
+  esac
+done
+
+CMD="$(which brightnessctl) --quiet"
+
+if (( "${SET}" != 0 )); then
+  sh -c "${CMD} set ${SET}%"
+elif [[ "${DOWN}" = true ]]; then
+  sh -c "${CMD} set ${LEVEL}-%"
+else
+  sh -c "${CMD} set +${LEVEL}%"
+fi
+
+echo "${UP}"
+echo "${DOWN}"
+echo "${LEVEL}"
+echo "${SET}"
